// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwR2tTXvtT8N13JN51IJC9gWFk6HOq92E',
    appId: '1:245343008853:ios:235356675097b5f12bbcdc',
    messagingSenderId: '245343008853',
    projectId: 'library-app-ca4ab',
    databaseURL: 'https://library-app-ca4ab-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-ca4ab.appspot.com',
    androidClientId: '245343008853-kgg2798jff7d9hn9ejrgsb52509h5pfs.apps.googleusercontent.com',
    iosClientId: '245343008853-33q2n7g8r363p5tgher3h8j99icupuiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAa0FS3u99KfNjenpXLwxQkEwwQGrcD54',
    appId: '1:245343008853:web:ee389f1ca6be5bd22bbcdc',
    messagingSenderId: '245343008853',
    projectId: 'library-app-ca4ab',
    authDomain: 'library-app-ca4ab.firebaseapp.com',
    databaseURL: 'https://library-app-ca4ab-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-ca4ab.appspot.com',
    measurementId: 'G-YKF2JYDQHS',
  );

}